version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tdin
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      # The standard AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"

  server:
    build: ./server
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - rabbitmq
    environment:
      WAIT_HOSTS: rabbitmq:5672, mongo:27017

  webapp:
    build: ./webapp
    restart: always
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./webapp:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - server
