version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tdin
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  # server:
  #   build:
  #     context: ./server
  #   volumes:
  #     - ./server/:/usr/scr/app
  #     - /usr/scr/app/node_modules
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - mongo