
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Windows
{
	public partial class Users
	{
		private global::Gtk.Alignment alignment1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HSeparator hseparator11;

		private global::Gtk.Label label1;

		private global::Gtk.HSeparator hseparator9;

		private global::Gtk.VBox requestList;

		private global::Gtk.HSeparator hseparator5;

		private global::Gtk.Label label3;

		private global::Gtk.HSeparator hseparator10;

		private global::Gtk.VBox userList;

		private global::Gtk.HSeparator hseparator7;

		private global::Gtk.Button logout;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Client.Windows.Users
			this.Name = "Client.Windows.Users";
			this.Title = global::Mono.Unix.Catalog.GetString("Users");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Client.Windows.Users.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(1));
			this.alignment1.TopPadding = ((uint)(1));
			this.alignment1.RightPadding = ((uint)(1));
			this.alignment1.BottomPadding = ((uint)(1));
			this.alignment1.BorderWidth = ((uint)(9));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator11 = new global::Gtk.HSeparator();
			this.hseparator11.Name = "hseparator11";
			this.vbox1.Add(this.hseparator11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Message Requests");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator9 = new global::Gtk.HSeparator();
			this.hseparator9.Name = "hseparator9";
			this.vbox1.Add(this.hseparator9);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator9]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.requestList = new global::Gtk.VBox();
			this.requestList.Name = "requestList";
			this.requestList.Spacing = 6;
			this.vbox1.Add(this.requestList);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.requestList]));
			w4.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator();
			this.hseparator5.Name = "hseparator5";
			this.vbox1.Add(this.hseparator5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator5]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Users Online");
			this.vbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label3]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator10 = new global::Gtk.HSeparator();
			this.hseparator10.Name = "hseparator10";
			this.vbox1.Add(this.hseparator10);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator10]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.userList = new global::Gtk.VBox();
			this.userList.Name = "userList";
			this.userList.Spacing = 6;
			this.vbox1.Add(this.userList);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.userList]));
			w8.Position = 7;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator7 = new global::Gtk.HSeparator();
			this.hseparator7.Name = "hseparator7";
			this.vbox1.Add(this.hseparator7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator7]));
			w9.Position = 8;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.logout = new global::Gtk.Button();
			this.logout.CanFocus = true;
			this.logout.Name = "logout";
			this.logout.UseUnderline = true;
			this.logout.Label = global::Mono.Unix.Catalog.GetString("Logout");
			this.vbox1.Add(this.logout);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.logout]));
			w10.Position = 9;
			w10.Expand = false;
			w10.Fill = false;
			this.alignment1.Add(this.vbox1);
			this.Add(this.alignment1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 334;
			this.DefaultHeight = 198;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.logout.Clicked += new global::System.EventHandler(this.OnLogoutClicked);
		}
	}
}
