
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Windows
{
	public partial class Chat
	{
		private global::Gtk.Alignment alignment1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView chatview;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry message;

		private global::Gtk.Button send;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Client.Windows.Chat
			this.Name = "Client.Windows.Chat";
			this.Title = global::Mono.Unix.Catalog.GetString("Chat");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Client.Windows.Chat.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(1));
			this.alignment1.TopPadding = ((uint)(1));
			this.alignment1.RightPadding = ((uint)(1));
			this.alignment1.BottomPadding = ((uint)(1));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.chatview = new global::Gtk.TextView();
			this.chatview.Name = "chatview";
			this.chatview.Editable = false;
			this.chatview.CursorVisible = false;
			this.chatview.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow.Add(this.chatview);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.message = new global::Gtk.Entry();
			this.message.CanFocus = true;
			this.message.Name = "message";
			this.message.IsEditable = true;
			this.message.InvisibleChar = '●';
			this.hbox1.Add(this.message);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.message]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.send = new global::Gtk.Button();
			this.send.CanFocus = true;
			this.send.Name = "send";
			this.send.UseUnderline = true;
			this.send.Label = global::Mono.Unix.Catalog.GetString("Send");
			this.hbox1.Add(this.send);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.send]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.alignment1.Add(this.vbox1);
			this.Add(this.alignment1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 387;
			this.DefaultHeight = 366;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.FocusInEvent += new global::Gtk.FocusInEventHandler(this.OnFocusInEvent);
			this.chatview.SizeAllocated += new global::Gtk.SizeAllocatedHandler(this.OnChatviewSizeAllocated);
			this.message.Activated += new global::System.EventHandler(this.OnMessageActivated);
			this.send.Clicked += new global::System.EventHandler(this.OnSendClicked);
		}
	}
}
