
// This file has been generated by the GUI designer. Do not modify.
namespace Client
{
	public partial class ChatWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action MenuAction;

		private global::Gtk.Action LogoutAction;

		private global::Gtk.Action ExitAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label1;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.TextView textview1;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label3;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.TextView textview2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Client.ChatWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.MenuAction = new global::Gtk.Action("MenuAction", global::Mono.Unix.Catalog.GetString("Menu"), null, null);
			this.MenuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menu");
			w1.Add(this.MenuAction, null);
			this.LogoutAction = new global::Gtk.Action("LogoutAction", global::Mono.Unix.Catalog.GetString("Logout"), null, null);
			this.LogoutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Logout");
			w1.Add(this.LogoutAction, null);
			this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
			this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
			w1.Add(this.ExitAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Client.ChatWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("ChatWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Client.ChatWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar1\'><menu><menu/><menuitem/></menu><menu name=\'MenuActio" +
					"n\' action=\'MenuAction\'><menuitem name=\'LogoutAction\' action=\'LogoutAction\'/><men" +
					"uitem name=\'ExitAction\' action=\'ExitAction\'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add(this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Chat Invitations");
			this.label1.UseUnderline = true;
			this.vbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.scrolledwindow2.Add(this.textview1);
			this.vbox2.Add(this.scrolledwindow2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow2]));
			w5.Position = 1;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w6.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Chat Friends");
			this.vbox4.Add(this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.textview2 = new global::Gtk.TextView();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.scrolledwindow1.Add(this.textview2);
			this.vbox4.Add(this.scrolledwindow1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.scrolledwindow1]));
			w10.Position = 1;
			this.vbox1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
			w11.Position = 3;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 626;
			this.DefaultHeight = 475;
			this.Show();
		}
	}
}
