
// This file has been generated by the GUI designer. Do not modify.
namespace Client.Windows
{
	public partial class Auth
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Fixed container;

		private global::Gtk.Entry username;

		private global::Gtk.Entry entry3;

		private global::Gtk.Button button1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Client.Windows.Auth
			this.Name = "Client.Windows.Auth";
			this.Title = global::Mono.Unix.Catalog.GetString("Auth");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Client.Windows.Auth.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.container = new global::Gtk.Fixed();
			this.container.Name = "container";
			this.container.HasWindow = false;
			// Container child container.Gtk.Fixed+FixedChild
			this.username = new global::Gtk.Entry();
			this.username.WidthRequest = 300;
			this.username.CanFocus = true;
			this.username.Name = "username";
			this.username.IsEditable = true;
			this.username.InvisibleChar = '●';
			this.container.Add(this.username);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.container[this.username]));
			w1.X = 100;
			w1.Y = 48;
			// Container child container.Gtk.Fixed+FixedChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.WidthRequest = 300;
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.container.Add(this.entry3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.container[this.entry3]));
			w2.X = 100;
			w2.Y = 150;
			// Container child container.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Login");
			this.container.Add(this.button1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.container[this.button1]));
			w3.X = 224;
			w3.Y = 219;
			// Container child container.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Username");
			this.container.Add(this.label1);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.container[this.label1]));
			w4.X = 119;
			w4.Y = 29;
			// Container child container.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Password");
			this.container.Add(this.label2);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.container[this.label2]));
			w5.X = 119;
			w5.Y = 131;
			this.vbox1.Add(this.container);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.container]));
			w6.Position = 0;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 485;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
